<style>
    header {
        position: sticky;
        top: 0;
    }
</style>
<header>
    <div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3">
            <div class="container-fluid">
                <a href="#" class="navbar-brand">
                    <span>JAYANKA.ME</span>
                </a>
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <div class="navbar-nav">
                        <a href="/" class="nav-item nav-link active">Home</a>
                        <a href="/resume" class="nav-item nav-link">Resume</a>
                    </div>
                </div>
            </div>
        </nav>
    </div>
</header>
