<html>
    <head>
        <?= renderTemplate(getFullPath('pub/templates/head.phtml')) ?>
        <style>
            body {
                background: #f0f0f0;
            }
        </style>
    </head>
    <body>
        <?= renderTemplate(getFullPath('pub/templates/header.phtml')) ?>
        <?= renderTemplate(getFullPath('pub/templates/body.phtml')) ?>
        <?= renderTemplate(getFullPath('pub/templates/footer.phtml')) ?>
    </body>
</html>
