<style>
    .social-links a {
        width: 100%;
        font-size: 1.4rem;
        margin-bottom: 1rem;
    }
    .social-links a i.fab {
        margin-right: 0.5rem;
    }
</style>
<div class="row mb-5">
    <div class="col-md-6">
        <img src="/pub/static/dp.jpg" class="rounded-circle w-75" />
    </div>
    <div class="col-md-6">
        <h1 class="display-1">Guitarist. Coder. Gamer</h1>
        <h3 class="display-6">Not necessarily in that order...</h3>
        <div class="row social-links mt-5">
            <div class="col-sm-4">
              <a class="btn btn-dark" href="https://github.com/jayankaghosh/" target="_blank"><i class="fab fa-github"></i> GitHub</a>
            </div>
            <div class="col-sm-4">
              <a class="btn btn-dark" href="https://www.linkedin.com/in/jayankaghosh/" target="_blank"><i class="fab fa-linkedin"></i> LinkedIn</a>
            </div>
            <div class="col-sm-4">
              <a class="btn btn-dark" href="https://www.facebook.com/jayankaghosh/" target="_blank"><i class="fab fa-facebook"></i> Facebook</a>
            </div>
        </div>
    </div>
</div>
<div>
    <p>An average cynical narcissist with a love for computers, guitars, and horror movies.</p>
    <p>If I'm being honest with you, I bought this domain since I was getting a good discount for it, and also I wanted a server to dump my sometimes-useful data on. So chances are that I've sent you this link personally, in which case, please feel free to roam around, and if you've stumbled on here by mistake, au revoir!</p>
</div>